In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("movie_dataset.csv")

In [8]:
df.shape

(4803, 24)

In [10]:
df.head(2)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski

In [11]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [16]:
features = ['keywords', 'cast','genres','director']

for feature in features:
    df[feature] = df[feature].fillna('')

In [17]:
def combine_feature(row):
    try:
        
        return row['keywords'] + " "+ row['cast'] + " "+ row['genres'] + " "+ row['director']
    except:
        print(row)

df['combined_features']=df.apply(combine_feature, axis =1)

In [18]:
df.iloc[0]['combined_features']

'culture clash future space war space colony society Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Action Adventure Fantasy Science Fiction James Cameron'

In [19]:
## step 2: Get the count matrix and apply cosine similarity

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

C:\Users\anili\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict

In [25]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
cosine_model = cosine_similarity(count_matrix)

In [26]:
cosine_model_df = pd.DataFrame(cosine_model)
cosine_model_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4793,4794,4795,4796,4797,4798,4799,4800,4801,4802
0,1.000000,0.105409,0.120386,0.037743,0.230940,0.192450,0.0,0.140546,0.082061,0.117851,...,0.000000,0.000000,0.000000,0.070273,0.000000,0.075485,0.0,0.000000,0.000000,0.0
1,0.105409,1.000000,0.076139,0.035806,0.073030,0.255604,0.0,0.066667,0.116775,0.111803,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.035806,0.0,0.036515,0.000000,0.0
2,0.120386,0.076139,1.000000,0.163572,0.208514,0.125109,0.0,0.190347,0.088911,0.170251,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.081786,0.0,0.000000,0.111456,0.0
3,0.037743,0.035806,0.163572,1.000000,0.039223,0.078446,0.0,0.035806,0.083624,0.120096,...,0.089984,0.050637,0.125436,0.107417,0.087706,0.153846,0.0,0.039223,0.000000,0.0
4,0.230940,0.073030,0.208514,0.039223,1.000000,0.200000,0.0,0.219089,0.042640,0.163299,...,0.000000,0.051640,0.000000,0.109545,0.000000,0.039223,0.0,0.000000,0.000000,0.0

In [27]:
cosine_model_df = pd.DataFrame(cosine_model, index = df.title, columns = df.title)
cosine_model_df.head()

title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter,Spider-Man 3,Tangled,Avengers: Age of Ultron,Harry Potter and the Half-Blood Prince,Batman v Superman: Dawn of Justice,...,On The Downlow,Sanctuary: Quite a Conundrum,Bang,Primer,Cavite,El Mariachi,Newlyweds,"Signed, Sealed, Delivered",Shanghai Calling,My Date with Drew
title,,,,,,,,,,,,,,,,,,,,,
Avatar,1.000000,0.105409,0.120386,0.037743,0.230940,0.192450,0.0,0.140546,0.082061,0.117851,...,0.000000,0.000000,0.000000,0.070273,0.000000,0.075485,0.0,0.000000,0.000000,0.0
Pirates of the Caribbean: At World's End,0.105409,1.000000,0.076139,0.035806,0.073030,0.255604,0.0,0.066667,0.116775,0.111803,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.035806,0.0,0.036515,0.000000,0.0
Spectre,0.120386,0.076139,1.000000,0.163572,0.208514,0.125109,0.0,0.190347,0.088911,0.170251,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.081786,0.0,0.000000,0.111456,0.0
The Dark Knight Rises,0.037743,0.035806,0.163572,1.000000,0.039223,0.078446,0.0,0.035806,0.083624,0.120096,...,0.089984,0.050637,0.125436,0.107417,0.087706,0.153846,0.0,0.039223,0.000000,0.0
John Carter,0.230940,0.073030,0.208514,0.039223,1.000000,0.200000,0.0,0.219089,0.042640,0.163299,...,0.000000,0.051640,0.000000,0.109545,0.000000,0.039223,0.0,0.000000,0.000000,0.0

In [28]:
## Step 3: Make Recommendations

In [34]:
def make_recommendations(movie_user_likes):
    return cosine_model_df[movie_user_likes].sort_values(ascending=False)[:20]

make_recommendations('Guardians of the Galaxy')

title
Guardians of the Galaxy                1.000000
Avatar                                 0.423390
Star Trek Into Darkness                0.402492
Star Trek Beyond                       0.392792
Avengers: Age of Ultron                0.328634
The Avengers                           0.323290
The Chronicles of Riddick              0.313786
The Helix... Loaded                    0.300000
X-Men: First Class                     0.298481
Captain America: The Winter Soldier    0.298481
Stargate: The Ark of Truth             0.298481
Star Trek                              0.298481
Wing Commander                         0.297113
Moonraker                              0.297113
X-Men: Days of Future Past             0.297113
Planet of the Apes                     0.292119
Gravity                                0.287368
Silent Running                         0.280000
Jason X                                0.280000
Star Wars: Clone Wars: Volume 1        0.280000
Name: Guardians of the Galaxy, dtype: float64

In [31]:
#Collarborative Filter